# Generated by Django 4.1.5 on 2023-06-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
