# Generated by Django 4.1.5 on 2023-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSpace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbqrcode',
            name='qrcode',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
