# Generated by Django 4.1.5 on 2023-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSpace', '0002_tbqrcode_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbperson',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tbperson',
            name='organDonor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbperson',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
