# Generated by Django 4.1.5 on 2023-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSpace', '0003_tbperson_height_tbperson_organdonor_tbperson_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbperson',
            name='birthDate',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
