# Generated by Django 4.1.5 on 2023-06-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSpace', '0003_alter_tbuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
